<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:connectorconfiguration="http://www.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_SFLYEFpIEfGye-OBcXLvfQ" name="MyDiagram" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_lKQLgFpIEfGye-OBcXLvfQ" name="Gestão Pedido">
      <elements xmi:type="process:Lane" xmi:id="_apdbYFpKEfGye-OBcXLvfQ" name="Programador" actor="_yTzJQF35EfGU_4a8meDJCw">
        <elements xmi:type="process:StartEvent" xmi:id="_jrBigFpKEfGye-OBcXLvfQ" name="Recebe um pedido" outgoing="_oGVFIF34EfGU_4a8meDJCw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jrBiglpKEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jrBigVpKEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jrBig1pKEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="__Ef1EFpKEfGye-OBcXLvfQ" name="Ajuste com um esforço de até 1 dia?" outgoing="_MeKIYFpMEfGye-OBcXLvfQ _hS01oF_oEfGm4rYpAOnikw" incoming="_hy-8YF_oEfGm4rYpAOnikw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2A5GkVpKEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2A5GkFpKEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2A5GklpKEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_OIIzYFpLEfGye-OBcXLvfQ" name="Tipo de pedido" outgoing="_RdYQ4VpLEfGye-OBcXLvfQ _R9yPS1pLEfGye-OBcXLvfQ _SllPG1pLEfGye-OBcXLvfQ" incoming="_QtzcwF_rEfGnB9X6Ra0WDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ghl4wVpLEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ghl4wFpLEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ghl4wlpLEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_SlkoAFpLEfGye-OBcXLvfQ" name="Encaminhar projetos (> 5 dias)" outgoing="_W5RcYFpMEfGye-OBcXLvfQ" incoming="_SllPG1pLEfGye-OBcXLvfQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SllPEVpLEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SllPEFpLEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SllPElpLEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_WT6I0GAbEfGe7t4W32Y_Cw" name="Send client notification" definitionId="email" event="ON_ENTER" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_WT6I0WAbEfGe7t4W32Y_Cw" definitionId="email" version="1.3.0" modelVersion="9">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I0mAbEfGe7t4W32Y_Cw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I02AbEfGe7t4W32Y_Cw" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I1GAbEfGe7t4W32Y_Cw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I1WAbEfGe7t4W32Y_Cw" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I1mAbEfGe7t4W32Y_Cw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I12AbEfGe7t4W32Y_Cw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I2GAbEfGe7t4W32Y_Cw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I2WAbEfGe7t4W32Y_Cw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I2mAbEfGe7t4W32Y_Cw" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I22AbEfGe7t4W32Y_Cw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I3GAbEfGe7t4W32Y_Cw" key="authType">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I3WAbEfGe7t4W32Y_Cw" name="Basic authentication" content="Basic authentication" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I3mAbEfGe7t4W32Y_Cw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I32AbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I4GAbEfGe7t4W32Y_Cw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I4WAbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I4mAbEfGe7t4W32Y_Cw" key="oauth2AccessToken">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I42AbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I5GAbEfGe7t4W32Y_Cw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I5WAbEfGe7t4W32Y_Cw" name="no-reply@acme.com" content="no-reply@acme.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I5mAbEfGe7t4W32Y_Cw" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I52AbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I6GAbEfGe7t4W32Y_Cw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I6WAbEfGe7t4W32Y_Cw" name="client@acme.com" content="client@acme.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I6mAbEfGe7t4W32Y_Cw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I62AbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I7GAbEfGe7t4W32Y_Cw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I7WAbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I7mAbEfGe7t4W32Y_Cw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I72AbEfGe7t4W32Y_Cw" name="O seu pedido deu origem a um projeto" content="O seu pedido deu origem a um projeto" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I8GAbEfGe7t4W32Y_Cw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I8WAbEfGe7t4W32Y_Cw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I8mAbEfGe7t4W32Y_Cw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I82AbEfGe7t4W32Y_Cw" name="&lt;pattern-expression>" content="" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I9GAbEfGe7t4W32Y_Cw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_WT6I9WAbEfGe7t4W32Y_Cw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I9mAbEfGe7t4W32Y_Cw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I92AbEfGe7t4W32Y_Cw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I-GAbEfGe7t4W32Y_Cw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_WT6I-WAbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_WT6I-mAbEfGe7t4W32Y_Cw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_WT6I-2AbEfGe7t4W32Y_Cw"/>
              </parameters>
            </configuration>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_k-3hYGAbEfGe7t4W32Y_Cw" name="Send manager notification" definitionId="email" event="ON_ENTER" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_k-3hYWAbEfGe7t4W32Y_Cw" definitionId="email" version="1.3.0" modelVersion="9">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hYmAbEfGe7t4W32Y_Cw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hY2AbEfGe7t4W32Y_Cw" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hZGAbEfGe7t4W32Y_Cw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hZWAbEfGe7t4W32Y_Cw" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hZmAbEfGe7t4W32Y_Cw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hZ2AbEfGe7t4W32Y_Cw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3haGAbEfGe7t4W32Y_Cw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_k-3haWAbEfGe7t4W32Y_Cw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hamAbEfGe7t4W32Y_Cw" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_k-3ha2AbEfGe7t4W32Y_Cw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hbGAbEfGe7t4W32Y_Cw" key="authType">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hbWAbEfGe7t4W32Y_Cw" name="Basic authentication" content="Basic authentication" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hbmAbEfGe7t4W32Y_Cw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hb2AbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hcGAbEfGe7t4W32Y_Cw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hcWAbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hcmAbEfGe7t4W32Y_Cw" key="oauth2AccessToken">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hc2AbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hdGAbEfGe7t4W32Y_Cw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hdWAbEfGe7t4W32Y_Cw" name="no-reply@acme.com" content="no-reply@acme.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hdmAbEfGe7t4W32Y_Cw" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hd2AbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3heGAbEfGe7t4W32Y_Cw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_k-3heWAbEfGe7t4W32Y_Cw" name="manager@acme.com" content="manager@acme.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hemAbEfGe7t4W32Y_Cw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_k-3he2AbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hfGAbEfGe7t4W32Y_Cw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hfWAbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hfmAbEfGe7t4W32Y_Cw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hf2AbEfGe7t4W32Y_Cw" name="Pedido enviado para a equipa de projetos" content="Pedido enviado para a equipa de projetos" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hgGAbEfGe7t4W32Y_Cw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hgWAbEfGe7t4W32Y_Cw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hgmAbEfGe7t4W32Y_Cw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hg2AbEfGe7t4W32Y_Cw" name="&lt;pattern-expression>" content="" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hhGAbEfGe7t4W32Y_Cw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_k-3hhWAbEfGe7t4W32Y_Cw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hhmAbEfGe7t4W32Y_Cw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hh2AbEfGe7t4W32Y_Cw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3hiGAbEfGe7t4W32Y_Cw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_k-3hiWAbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_k-3himAbEfGe7t4W32Y_Cw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_k-3hi2AbEfGe7t4W32Y_Cw"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SllPE1pLEfGye-OBcXLvfQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SllPFFpLEfGye-OBcXLvfQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SllPFVpLEfGye-OBcXLvfQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SllPF1pLEfGye-OBcXLvfQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SllPFlpLEfGye-OBcXLvfQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_JqDCAFpMEfGye-OBcXLvfQ" name="Fechar" outgoing="__Pz5MF6oEfGm4rYpAOnikw" incoming="_DB4bN1pMEfGye-OBcXLvfQ _KVkrQFpMEfGye-OBcXLvfQ _MeKIYFpMEfGye-OBcXLvfQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DB4bMVpMEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DB4bMFpMEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DB4bMlpMEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_TWhuYFpMEfGye-OBcXLvfQ" name="Fim" incoming="__v1dEF6oEfGm4rYpAOnikw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TWiVcVpMEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TWiVcFpMEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TWiVclpMEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_W5Q1UFpMEfGye-OBcXLvfQ" name="Informação detalhada do pedido encaminhada para a equipa comercial" incoming="_W5RcYFpMEfGye-OBcXLvfQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_W5Q1UlpMEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_W5Q1UVpMEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_W5Q1U1pMEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_qBgDQF32EfG6RKjpA2FJ2g" name="Validar estimativa de melhoria (1 a 3 dias)" outgoing="_DB4bN1pMEfGye-OBcXLvfQ" incoming="_R9yPS1pLEfGye-OBcXLvfQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_R9yPQVpLEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_R9yPQFpLEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_R9yPQlpLEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_R9yPQ1pLEfGye-OBcXLvfQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_R9yPRFpLEfGye-OBcXLvfQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_R9yPRVpLEfGye-OBcXLvfQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_R9yPR1pLEfGye-OBcXLvfQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_R9yPRlpLEfGye-OBcXLvfQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_qjZ2cF32EfG6RKjpA2FJ2g" name="Aprovar alterações funcionais (3 a 5 dias)" outgoing="_KVkrQFpMEfGye-OBcXLvfQ" incoming="_RdYQ4VpLEfGye-OBcXLvfQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_RdXp0lpLEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_RdXp0VpLEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_RdXp01pLEfGye-OBcXLvfQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_Ly7dYGAbEfGe7t4W32Y_Cw" name="Send client notification" definitionId="email" event="ON_ENTER" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_Ly7dYWAbEfGe7t4W32Y_Cw" definitionId="email" version="1.3.0" modelVersion="9">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7dYmAbEfGe7t4W32Y_Cw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7dY2AbEfGe7t4W32Y_Cw" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7dZGAbEfGe7t4W32Y_Cw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7dZWAbEfGe7t4W32Y_Cw" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7dZmAbEfGe7t4W32Y_Cw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7dZ2AbEfGe7t4W32Y_Cw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7daGAbEfGe7t4W32Y_Cw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7daWAbEfGe7t4W32Y_Cw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7damAbEfGe7t4W32Y_Cw" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7da2AbEfGe7t4W32Y_Cw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7dbGAbEfGe7t4W32Y_Cw" key="authType">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7dbWAbEfGe7t4W32Y_Cw" name="Basic authentication" content="Basic authentication" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7dbmAbEfGe7t4W32Y_Cw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7db2AbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7dcGAbEfGe7t4W32Y_Cw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7dcWAbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7dcmAbEfGe7t4W32Y_Cw" key="oauth2AccessToken">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7dc2AbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7ddGAbEfGe7t4W32Y_Cw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7ddWAbEfGe7t4W32Y_Cw" name="no-reply@acme.com" content="no-reply@acme.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7ddmAbEfGe7t4W32Y_Cw" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7dd2AbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7deGAbEfGe7t4W32Y_Cw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7deWAbEfGe7t4W32Y_Cw" name="client@acme.com" content="client@acme.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7demAbEfGe7t4W32Y_Cw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7de2AbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7dfGAbEfGe7t4W32Y_Cw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7dfWAbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7dfmAbEfGe7t4W32Y_Cw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7df2AbEfGe7t4W32Y_Cw" name="O seu pedido deu origem a uma alteração" content="O seu pedido deu origem a uma alteração" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7dgGAbEfGe7t4W32Y_Cw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7dgWAbEfGe7t4W32Y_Cw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7dgmAbEfGe7t4W32Y_Cw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7dg2AbEfGe7t4W32Y_Cw" name="&lt;pattern-expression>" content="" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7dhGAbEfGe7t4W32Y_Cw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_Ly7dhWAbEfGe7t4W32Y_Cw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7dhmAbEfGe7t4W32Y_Cw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7dh2AbEfGe7t4W32Y_Cw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7diGAbEfGe7t4W32Y_Cw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_Ly7diWAbEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Ly7dimAbEfGe7t4W32Y_Cw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_Ly7di2AbEfGe7t4W32Y_Cw"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_RdXp1FpLEfGye-OBcXLvfQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_RdXp1VpLEfGye-OBcXLvfQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RdXp1lpLEfGye-OBcXLvfQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_RdXp2FpLEfGye-OBcXLvfQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_RdXp11pLEfGye-OBcXLvfQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_nbkQ4F34EfGU_4a8meDJCw" name="Classificar Pedido" outgoing="_hy-8YF_oEfGm4rYpAOnikw" incoming="_oGVFIF34EfGU_4a8meDJCw" actor="_yTzJQF35EfGU_4a8meDJCw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nbn7QV34EfGU_4a8meDJCw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nbn7QF34EfGU_4a8meDJCw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nbn7Ql34EfGU_4a8meDJCw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_JShFA1_tEfGnB9X6Ra0WDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JShFBF_tEfGnB9X6Ra0WDg" name="pedido" content="pedido" type="TYPE_VARIABLE" returnType="com.company.model.Pedido">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JShFBV_tEfGnB9X6Ra0WDg" name="pedido" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.Pedido"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JShFBl_tEfGnB9X6Ra0WDg" name="pedidoInput.tipo" content="pedidoInput?.tipo" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JShFB1_tEfGnB9X6Ra0WDg" name="pedidoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JShFCF_tEfGnB9X6Ra0WDg" type="JAVA_METHOD" expression="setTipo">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_JShFCV_tEfGnB9X6Ra0WDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JShFCl_tEfGnB9X6Ra0WDg" name="pedido" content="pedido" type="TYPE_VARIABLE" returnType="com.company.model.Pedido">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JShFC1_tEfGnB9X6Ra0WDg" name="pedido" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.Pedido"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JShFDF_tEfGnB9X6Ra0WDg" name="pedidoInput.estimativaDias" content="pedidoInput?.estimativaDias" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_JShFDV_tEfGnB9X6Ra0WDg" name="pedidoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JShFDl_tEfGnB9X6Ra0WDg" type="JAVA_METHOD" expression="setEstimativaDias">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_nbn7Q134EfGU_4a8meDJCw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_nbn7RF34EfGU_4a8meDJCw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_nbn7RV34EfGU_4a8meDJCw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_nbn7R134EfGU_4a8meDJCw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_nbn7Rl34EfGU_4a8meDJCw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_nbn7SV34EfGU_4a8meDJCw">
            <targetForm xmi:type="expression:Expression" xmi:id="_TLh44F_qEfGnB9X6Ra0WDg" name="FormProgramadorClassificarPedido" content="7ba6e0f8-ec6b-4a24-8c6e-35e603f253f4" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_nbn7SF34EfGU_4a8meDJCw">
            <inputs xmi:type="process:ContractInput" xmi:id="_JShFAF_tEfGnB9X6Ra0WDg" name="pedidoInput" type="COMPLEX" dataReference="pedido" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_JShFAV_tEfGnB9X6Ra0WDg" name="tipo" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JShFAl_tEfGnB9X6Ra0WDg" name="estimativaDias" type="INTEGER" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_nbn7S134EfGU_4a8meDJCw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_qBiYkF_wEfGdK7nrvVK6_Q" name="Executar Tarefa" outgoing="__v1dEF6oEfGm4rYpAOnikw" incoming="__Pz5MF6oEfGm4rYpAOnikw" type="STANDARD" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8yosIV6oEfGm4rYpAOnikw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8yosIl6oEfGm4rYpAOnikw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8yosI16oEfGm4rYpAOnikw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_RWMDsF_xEfGdK7nrvVK6_Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_RWMDsV_xEfGdK7nrvVK6_Q" name="registarHoras" content="registarHoras" type="TYPE_VARIABLE" returnType="com.company.model.RegistarHoras">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_RWMDsl_xEfGdK7nrvVK6_Q" name="registarHoras" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.RegistarHoras"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_RWMDs1_xEfGdK7nrvVK6_Q" name="registarHorasInput.horas" content="registarHorasInput?.horas" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_RWMDtF_xEfGdK7nrvVK6_Q" name="registarHorasInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_RWMDtV_xEfGdK7nrvVK6_Q" type="JAVA_METHOD" expression="setHoras">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_S3eQQV_xEfGdK7nrvVK6_Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_S3eQQl_xEfGdK7nrvVK6_Q" name="pedido" content="pedido" type="TYPE_VARIABLE" returnType="com.company.model.Pedido">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_S3eQQ1_xEfGdK7nrvVK6_Q" name="pedido" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.Pedido"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_S3eQRF_xEfGdK7nrvVK6_Q" name="pedidoInput.finalizado" content="pedidoInput?.finalizado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_S3eQRV_xEfGdK7nrvVK6_Q" name="pedidoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_S3eQRl_xEfGdK7nrvVK6_Q" type="JAVA_METHOD" expression="setFinalizado">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_V5b6gF_zEfGdK7nrvVK6_Q">
            <leftOperand xmi:type="expression:Expression" xmi:id="_V5b6gV_zEfGdK7nrvVK6_Q" name="tarefaFinalizada" content="tarefaFinalizada" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_X2onAF_zEfGdK7nrvVK6_Q" name="tarefaFinalizada" dataType="_SFLYPFpIEfGye-OBcXLvfQ"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_V5b6gl_zEfGdK7nrvVK6_Q" name="newScript()" content="pedido.finalizado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1_vy0F_3EfGugaLECWMYaw" name="pedido" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.Pedido"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_V5b6g1_zEfGdK7nrvVK6_Q" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8yosJF6oEfGm4rYpAOnikw" name="loopWhile()" content="!tarefaFinalizada" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
            <referencedElements xmi:type="process:Data" xmi:id="_EXmpMF_4EfGugaLECWMYaw" name="tarefaFinalizada" dataType="_SFLYPFpIEfGye-OBcXLvfQ"/>
          </loopCondition>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8yosJV6oEfGm4rYpAOnikw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8yosJl6oEfGm4rYpAOnikw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8yosJ16oEfGm4rYpAOnikw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8yosKF6oEfGm4rYpAOnikw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_qBswqV_wEfGdK7nrvVK6_Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_UY7b8F_xEfGdK7nrvVK6_Q" name="FormExecutarTarefaProgramador" content="9b525531-4b1d-4fd5-a5ce-67599f5f02dc" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_qBswqF_wEfGdK7nrvVK6_Q">
            <inputs xmi:type="process:ContractInput" xmi:id="_RWLcoF_xEfGdK7nrvVK6_Q" name="registarHorasInput" type="COMPLEX" dataReference="registarHoras" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_RWLcoV_xEfGdK7nrvVK6_Q" name="horas" type="INTEGER" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_S3dpMF_xEfGdK7nrvVK6_Q" name="pedidoInput" type="COMPLEX" dataReference="pedido" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_S3eQQF_xEfGdK7nrvVK6_Q" name="finalizado" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_qBtXsV_wEfGdK7nrvVK6_Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_WEdLIF6oEfGm4rYpAOnikw" name="Gestor" actor="_Yvz-IF6oEfGm4rYpAOnikw">
        <elements xmi:type="process:Task" xmi:id="_cBPSoF6oEfGm4rYpAOnikw" name="Analisar Classificação do Programador" outgoing="_PdBKUF_rEfGnB9X6Ra0WDg" incoming="_hS01oF_oEfGm4rYpAOnikw" actor="_Yvz-IF6oEfGm4rYpAOnikw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_cBPSoV6oEfGm4rYpAOnikw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_cBPSol6oEfGm4rYpAOnikw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_cBPSo16oEfGm4rYpAOnikw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_PtF7xV_tEfGnB9X6Ra0WDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PtF7xl_tEfGnB9X6Ra0WDg" name="pedido" content="pedido" type="TYPE_VARIABLE" returnType="com.company.model.Pedido">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PtF7x1_tEfGnB9X6Ra0WDg" name="pedido" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.Pedido"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PtF7yF_tEfGnB9X6Ra0WDg" name="pedidoInput.tipo" content="pedidoInput?.tipo" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PtF7yV_tEfGnB9X6Ra0WDg" name="pedidoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PtF7yl_tEfGnB9X6Ra0WDg" type="JAVA_METHOD" expression="setTipo">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PtF7y1_tEfGnB9X6Ra0WDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PtF7zF_tEfGnB9X6Ra0WDg" name="pedido" content="pedido" type="TYPE_VARIABLE" returnType="com.company.model.Pedido">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PtF7zV_tEfGnB9X6Ra0WDg" name="pedido" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.Pedido"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PtF7zl_tEfGnB9X6Ra0WDg" name="pedidoInput.estimativaDias" content="pedidoInput?.estimativaDias" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PtF7z1_tEfGnB9X6Ra0WDg" name="pedidoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PtF70F_tEfGnB9X6Ra0WDg" type="JAVA_METHOD" expression="setEstimativaDias">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PtF70V_tEfGnB9X6Ra0WDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PtF70l_tEfGnB9X6Ra0WDg" name="pedido" content="pedido" type="TYPE_VARIABLE" returnType="com.company.model.Pedido">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PtF701_tEfGnB9X6Ra0WDg" name="pedido" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.Pedido"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PtF71F_tEfGnB9X6Ra0WDg" name="pedidoInput.classificacaoValida" content="pedidoInput?.classificacaoValida" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PtF71V_tEfGnB9X6Ra0WDg" name="pedidoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PtF71l_tEfGnB9X6Ra0WDg" type="JAVA_METHOD" expression="setClassificacaoValida">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_PtF711_tEfGnB9X6Ra0WDg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_PtF72F_tEfGnB9X6Ra0WDg" name="pedido" content="pedido" type="TYPE_VARIABLE" returnType="com.company.model.Pedido">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PtF72V_tEfGnB9X6Ra0WDg" name="pedido" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.Pedido"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_PtF72l_tEfGnB9X6Ra0WDg" name="pedidoInput.observacoesGestor" content="pedidoInput?.observacoesGestor" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_PtF721_tEfGnB9X6Ra0WDg" name="pedidoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_PtF73F_tEfGnB9X6Ra0WDg" type="JAVA_METHOD" expression="setObservacoesGestor">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_cBP5wl6oEfGm4rYpAOnikw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_cBP5w16oEfGm4rYpAOnikw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_cBP5xF6oEfGm4rYpAOnikw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_cBP5xV6oEfGm4rYpAOnikw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_cBP5xl6oEfGm4rYpAOnikw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_cBP5x16oEfGm4rYpAOnikw">
            <targetForm xmi:type="expression:Expression" xmi:id="_yANuEF_qEfGnB9X6Ra0WDg" name="FormGestorAnalisarPedido" content="d9a42a0f-c42d-4911-9779-d4876c9a68e5" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_cBP5yV6oEfGm4rYpAOnikw">
            <inputs xmi:type="process:ContractInput" xmi:id="_PtF7wF_tEfGnB9X6Ra0WDg" name="pedidoInput" type="COMPLEX" dataReference="pedido" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_PtF7wV_tEfGnB9X6Ra0WDg" name="tipo" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PtF7wl_tEfGnB9X6Ra0WDg" name="estimativaDias" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PtF7w1_tEfGnB9X6Ra0WDg" name="classificacaoValida" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_PtF7xF_tEfGnB9X6Ra0WDg" name="observacoesGestor" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_cBP5z16oEfGm4rYpAOnikw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ND0eUF_rEfGnB9X6Ra0WDg" name="Pedido Rejeitado ?" outgoing="_QtzcwF_rEfGnB9X6Ra0WDg _UNlWUF_rEfGnB9X6Ra0WDg" incoming="_PdBKUF_rEfGnB9X6Ra0WDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ND0eUV_rEfGnB9X6Ra0WDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ND0eUl_rEfGnB9X6Ra0WDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ND0eU1_rEfGnB9X6Ra0WDg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_XXefcF_rEfGnB9X6Ra0WDg" name="Pedido Rejeitado" incoming="_Z_BJcF_rEfGnB9X6Ra0WDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XXefcV_rEfGnB9X6Ra0WDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XXefcl_rEfGnB9X6Ra0WDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XXefc1_rEfGnB9X6Ra0WDg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_R_SZUGAYEfGe7t4W32Y_Cw" name="Enviar Email Cliente A dizer pedido Rejeitado" outgoing="_Z_BJcF_rEfGnB9X6Ra0WDg" incoming="_UNlWUF_rEfGnB9X6Ra0WDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_RvAbEV_rEfGnB9X6Ra0WDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_RvAbEl_rEfGnB9X6Ra0WDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_RvAbE1_rEfGnB9X6Ra0WDg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_G_5eIGAZEfGe7t4W32Y_Cw" name="Send client notification" definitionId="email" event="ON_ENTER" namedError="Error sending notification" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_G_5eIWAZEfGe7t4W32Y_Cw" definitionId="email" version="1.3.0" modelVersion="9">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eImAZEfGe7t4W32Y_Cw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eI2AZEfGe7t4W32Y_Cw" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eJGAZEfGe7t4W32Y_Cw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eJWAZEfGe7t4W32Y_Cw" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eJmAZEfGe7t4W32Y_Cw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eJ2AZEfGe7t4W32Y_Cw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eKGAZEfGe7t4W32Y_Cw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eKWAZEfGe7t4W32Y_Cw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eKmAZEfGe7t4W32Y_Cw" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eK2AZEfGe7t4W32Y_Cw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eLGAZEfGe7t4W32Y_Cw" key="authType">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eLWAZEfGe7t4W32Y_Cw" name="Basic authentication" content="Basic authentication" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eLmAZEfGe7t4W32Y_Cw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eL2AZEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eMGAZEfGe7t4W32Y_Cw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eMWAZEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eMmAZEfGe7t4W32Y_Cw" key="oauth2AccessToken">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eM2AZEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eNGAZEfGe7t4W32Y_Cw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eNWAZEfGe7t4W32Y_Cw" name="no-reply@acme.com" content="no-reply@acme.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eNmAZEfGe7t4W32Y_Cw" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eN2AZEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eOGAZEfGe7t4W32Y_Cw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eOWAZEfGe7t4W32Y_Cw" name="client@acme.com" content="client@acme.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eO2AZEfGe7t4W32Y_Cw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_G_5ePGAZEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5ePWAZEfGe7t4W32Y_Cw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_G_5ePmAZEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eP2AZEfGe7t4W32Y_Cw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eQGAZEfGe7t4W32Y_Cw" name="O seu pedido foi rejeitado" content="O seu pedido foi rejeitado" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eQWAZEfGe7t4W32Y_Cw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eQmAZEfGe7t4W32Y_Cw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eQ2AZEfGe7t4W32Y_Cw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eRGAZEfGe7t4W32Y_Cw" name="&lt;pattern-expression>" content="" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eRWAZEfGe7t4W32Y_Cw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_G_5eRmAZEfGe7t4W32Y_Cw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eR2AZEfGe7t4W32Y_Cw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eSGAZEfGe7t4W32Y_Cw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eSWAZEfGe7t4W32Y_Cw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_G_5eSmAZEfGe7t4W32Y_Cw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_G_5eS2AZEfGe7t4W32Y_Cw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_G_5eTGAZEfGe7t4W32Y_Cw"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_RvAbFF_rEfGnB9X6Ra0WDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_RvAbFV_rEfGnB9X6Ra0WDg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RvAbFl_rEfGnB9X6Ra0WDg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_RvAbF1_rEfGnB9X6Ra0WDg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_RvAbGF_rEfGnB9X6Ra0WDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="__j4cgF_sEfGnB9X6Ra0WDg" name="pedido" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.Pedido">
        <defaultValue xmi:type="expression:Expression" xmi:id="_bQ2n8F_vEfGdK7nrvVK6_Q" name="initpedido()" content="def pedidoVar = new com.company.model.Pedido()&#xD;&#xA;pedidoVar.titulo = pedidoInput?.titulo&#xD;&#xA;pedidoVar.descricao = pedidoInput?.descricao&#xD;&#xA;pedidoVar.tipo = pedidoInput?.tipo&#xD;&#xA;pedidoVar.estimativaDias = pedidoInput?.estimativaDias&#xD;&#xA;return pedidoVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Pedido">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_hlubIF_2EfGEZJDM3Gbx_g" name="pedidoInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_MVRHgF_xEfGdK7nrvVK6_Q" name="registarHoras" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.RegistarHoras">
        <defaultValue xmi:type="expression:Expression" xmi:id="_MVRHgV_xEfGdK7nrvVK6_Q" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_UkJikF_zEfGdK7nrvVK6_Q" name="tarefaFinalizada" dataType="_SFLYPFpIEfGye-OBcXLvfQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_UkJikV_zEfGdK7nrvVK6_Q" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_lKT171pIEfGye-OBcXLvfQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_M2zgkF_sEfGnB9X6Ra0WDg" name="FormPedido" content="e2ccef01-da5c-4925-b0f1-0059ee396cab" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_lKT18VpIEfGye-OBcXLvfQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_lKT18lpIEfGye-OBcXLvfQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RdYQ4VpLEfGye-OBcXLvfQ" name="Alteração funcional" target="_qjZ2cF32EfG6RKjpA2FJ2g" source="_OIIzYFpLEfGye-OBcXLvfQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RdYQ4lpLEfGye-OBcXLvfQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_RdYQ41pLEfGye-OBcXLvfQ" name="newScript()" content="pedido.tipo==&quot;ALTERACAO_FUNCIONAL&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_MduRMF_3EfGugaLECWMYaw" name="pedido" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.Pedido"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_R9yPS1pLEfGye-OBcXLvfQ" name="Melhoria" target="_qBgDQF32EfG6RKjpA2FJ2g" source="_OIIzYFpLEfGye-OBcXLvfQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_R9yPTFpLEfGye-OBcXLvfQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_R9yPTVpLEfGye-OBcXLvfQ" name="pedido.tipo==&quot;MELHORIA&quot;" content="pedido.tipo==&quot;MELHORIA&quot;" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SllPG1pLEfGye-OBcXLvfQ" name="Projeto" target="_SlkoAFpLEfGye-OBcXLvfQ" source="_OIIzYFpLEfGye-OBcXLvfQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SllPHFpLEfGye-OBcXLvfQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_SllPHVpLEfGye-OBcXLvfQ" name="newScript()" content="pedido.tipo==&quot;PROJETO&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_OSurAF_3EfGugaLECWMYaw" name="pedido" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.Pedido"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DB4bN1pMEfGye-OBcXLvfQ" target="_JqDCAFpMEfGye-OBcXLvfQ" source="_qBgDQF32EfG6RKjpA2FJ2g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DB5CQFpMEfGye-OBcXLvfQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_DB5CQVpMEfGye-OBcXLvfQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KVkrQFpMEfGye-OBcXLvfQ" target="_JqDCAFpMEfGye-OBcXLvfQ" source="_qjZ2cF32EfG6RKjpA2FJ2g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KVkrQVpMEfGye-OBcXLvfQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_KVkrQlpMEfGye-OBcXLvfQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MeKIYFpMEfGye-OBcXLvfQ" name="Sim" target="_JqDCAFpMEfGye-OBcXLvfQ" source="__Ef1EFpKEfGye-OBcXLvfQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MeKIYVpMEfGye-OBcXLvfQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_MeKIYlpMEfGye-OBcXLvfQ" name="newScript()" content="pedido.estimativaDias &lt;= 1" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_zSFvMF_2EfGEZJDM3Gbx_g" name="pedido" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.Pedido"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_W5RcYFpMEfGye-OBcXLvfQ" target="_W5Q1UFpMEfGye-OBcXLvfQ" source="_SlkoAFpLEfGye-OBcXLvfQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_W5RcYVpMEfGye-OBcXLvfQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_W5RcYlpMEfGye-OBcXLvfQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oGVFIF34EfGU_4a8meDJCw" target="_nbkQ4F34EfGU_4a8meDJCw" source="_jrBigFpKEfGye-OBcXLvfQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oGVsMF34EfGU_4a8meDJCw"/>
        <condition xmi:type="expression:Expression" xmi:id="_oGVsMV34EfGU_4a8meDJCw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__Pz5MF6oEfGm4rYpAOnikw" target="_qBiYkF_wEfGdK7nrvVK6_Q" source="_JqDCAFpMEfGye-OBcXLvfQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__Pz5MV6oEfGm4rYpAOnikw"/>
        <condition xmi:type="expression:Expression" xmi:id="__Pz5Ml6oEfGm4rYpAOnikw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__v1dEF6oEfGm4rYpAOnikw" target="_TWhuYFpMEfGye-OBcXLvfQ" source="_qBiYkF_wEfGdK7nrvVK6_Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__v1dEV6oEfGm4rYpAOnikw"/>
        <condition xmi:type="expression:Expression" xmi:id="__v1dEl6oEfGm4rYpAOnikw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hS01oF_oEfGm4rYpAOnikw" name="Não" target="_cBPSoF6oEfGm4rYpAOnikw" source="__Ef1EFpKEfGye-OBcXLvfQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hS01oV_oEfGm4rYpAOnikw"/>
        <condition xmi:type="expression:Expression" xmi:id="_hS01ol_oEfGm4rYpAOnikw" name="pedido.estimativaDias>1" content="pedido.estimativaDias>1" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hy-8YF_oEfGm4rYpAOnikw" target="__Ef1EFpKEfGye-OBcXLvfQ" source="_nbkQ4F34EfGU_4a8meDJCw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hy_jcF_oEfGm4rYpAOnikw"/>
        <condition xmi:type="expression:Expression" xmi:id="_hy_jcV_oEfGm4rYpAOnikw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PdBKUF_rEfGnB9X6Ra0WDg" target="_ND0eUF_rEfGnB9X6Ra0WDg" source="_cBPSoF6oEfGm4rYpAOnikw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PdBKUV_rEfGnB9X6Ra0WDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_PdBKUl_rEfGnB9X6Ra0WDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QtzcwF_rEfGnB9X6Ra0WDg" name="Não" target="_OIIzYFpLEfGye-OBcXLvfQ" source="_ND0eUF_rEfGnB9X6Ra0WDg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QtzcwV_rEfGnB9X6Ra0WDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Qtzcwl_rEfGnB9X6Ra0WDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UNlWUF_rEfGnB9X6Ra0WDg" name="Sim" target="_R_SZUGAYEfGe7t4W32Y_Cw" source="_ND0eUF_rEfGnB9X6Ra0WDg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UNlWUV_rEfGnB9X6Ra0WDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_UNlWUl_rEfGnB9X6Ra0WDg" name="newScript()" content="!pedido.classificacaoValida" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QNHUEF_3EfGugaLECWMYaw" name="pedido" dataType="_SFLYRFpIEfGye-OBcXLvfQ" className="com.company.model.Pedido"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Z_BJcF_rEfGnB9X6Ra0WDg" target="_XXefcF_rEfGnB9X6Ra0WDg" source="_R_SZUGAYEfGe7t4W32Y_Cw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Z_BJcV_rEfGnB9X6Ra0WDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Z_BJcl_rEfGnB9X6Ra0WDg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_yTzJQF35EfGU_4a8meDJCw" name="Programador" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_Yvz-IF6oEfGm4rYpAOnikw" name="Gestor"/>
      <contract xmi:type="process:Contract" xmi:id="_lKT181pIEfGye-OBcXLvfQ">
        <inputs xmi:type="process:ContractInput" xmi:id="_bQ2A4F_vEfGdK7nrvVK6_Q" name="pedidoInput" type="COMPLEX" dataReference="pedido">
          <inputs xmi:type="process:ContractInput" xmi:id="_bQ2A4V_vEfGdK7nrvVK6_Q" name="titulo"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_bQ2A4l_vEfGdK7nrvVK6_Q" name="descricao"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lKT14FpIEfGye-OBcXLvfQ">
        <name xmi:type="expression:Expression" xmi:id="_lKT14VpIEfGye-OBcXLvfQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lKT14lpIEfGye-OBcXLvfQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lKT141pIEfGye-OBcXLvfQ">
        <name xmi:type="expression:Expression" xmi:id="_lKT15FpIEfGye-OBcXLvfQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lKT15VpIEfGye-OBcXLvfQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lKT15lpIEfGye-OBcXLvfQ">
        <name xmi:type="expression:Expression" xmi:id="_lKT151pIEfGye-OBcXLvfQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lKT16FpIEfGye-OBcXLvfQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lKT16VpIEfGye-OBcXLvfQ">
        <name xmi:type="expression:Expression" xmi:id="_lKT16lpIEfGye-OBcXLvfQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lKT161pIEfGye-OBcXLvfQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lKT17FpIEfGye-OBcXLvfQ">
        <name xmi:type="expression:Expression" xmi:id="_lKT17VpIEfGye-OBcXLvfQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lKT17lpIEfGye-OBcXLvfQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_SFLYPFpIEfGye-OBcXLvfQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_SFLYPVpIEfGye-OBcXLvfQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_SFLYPlpIEfGye-OBcXLvfQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_SFLYP1pIEfGye-OBcXLvfQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_SFLYQFpIEfGye-OBcXLvfQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_SFLYQVpIEfGye-OBcXLvfQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_SFLYQlpIEfGye-OBcXLvfQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_SFLYQ1pIEfGye-OBcXLvfQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_SFLYRFpIEfGye-OBcXLvfQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_SFLYRVpIEfGye-OBcXLvfQ" type="Process" element="_SFLYEFpIEfGye-OBcXLvfQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_lKqbMFpIEfGye-OBcXLvfQ" type="2007" element="_lKQLgFpIEfGye-OBcXLvfQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_lKrCQFpIEfGye-OBcXLvfQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_lKrCQVpIEfGye-OBcXLvfQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_apepgFpKEfGye-OBcXLvfQ" type="3007" element="_apdbYFpKEfGye-OBcXLvfQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_apephVpKEfGye-OBcXLvfQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_apephlpKEfGye-OBcXLvfQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_jrCJkFpKEfGye-OBcXLvfQ" type="3002" element="_jrBigFpKEfGye-OBcXLvfQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jrCJklpKEfGye-OBcXLvfQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jrCJk1pKEfGye-OBcXLvfQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jrCJkVpKEfGye-OBcXLvfQ" x="56" y="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__Ef1FFpKEfGye-OBcXLvfQ" type="3008" element="__Ef1EFpKEfGye-OBcXLvfQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="__Ef1FlpKEfGye-OBcXLvfQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="__Ef1F1pKEfGye-OBcXLvfQ" x="58" y="-58"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__Ef1FVpKEfGye-OBcXLvfQ" x="379" y="69" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OIJacFpLEfGye-OBcXLvfQ" type="3008" element="_OIIzYFpLEfGye-OBcXLvfQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_OIJaclpLEfGye-OBcXLvfQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_OIJac1pLEfGye-OBcXLvfQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OIJacVpLEfGye-OBcXLvfQ" x="778" y="212" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SllPGFpLEfGye-OBcXLvfQ" type="3027" element="_SlkoAFpLEfGye-OBcXLvfQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SllPGlpLEfGye-OBcXLvfQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SllPGVpLEfGye-OBcXLvfQ" x="972" y="294" width="188" height="94"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JqDCBFpMEfGye-OBcXLvfQ" type="3008" element="_JqDCAFpMEfGye-OBcXLvfQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_JqDpEFpMEfGye-OBcXLvfQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_JqDpEVpMEfGye-OBcXLvfQ" x="-56" y="-21"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JqDCBVpMEfGye-OBcXLvfQ" x="1234" y="152" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TWi8gFpMEfGye-OBcXLvfQ" type="3003" element="_TWhuYFpMEfGye-OBcXLvfQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_TWi8glpMEfGye-OBcXLvfQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_TWi8g1pMEfGye-OBcXLvfQ" x="-4" y="-50"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TWi8gVpMEfGye-OBcXLvfQ" x="1633" y="153"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_W5Q1VFpMEfGye-OBcXLvfQ" type="3003" element="_W5Q1UFpMEfGye-OBcXLvfQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_W5Q1VlpMEfGye-OBcXLvfQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_W5Q1V1pMEfGye-OBcXLvfQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_W5Q1VVpMEfGye-OBcXLvfQ" x="1595" y="331"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qBhRYF32EfG6RKjpA2FJ2g" type="3027" element="_qBgDQF32EfG6RKjpA2FJ2g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qBh4cF32EfG6RKjpA2FJ2g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qBhRYV32EfG6RKjpA2FJ2g" x="969" y="69" width="181" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qjadiF32EfG6RKjpA2FJ2g" type="3027" element="_qjZ2cF32EfG6RKjpA2FJ2g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qjadil32EfG6RKjpA2FJ2g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qjadiV32EfG6RKjpA2FJ2g" x="968" y="187" width="184" height="92"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nbrloF34EfGU_4a8meDJCw" type="3005" element="_nbkQ4F34EfGU_4a8meDJCw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_nbsMsF34EfGU_4a8meDJCw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nbrloV34EfGU_4a8meDJCw" x="113" y="53" width="156" height="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qB3vwF_wEfGdK7nrvVK6_Q" type="3005" element="_qBiYkF_wEfGdK7nrvVK6_Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qB3vwl_wEfGdK7nrvVK6_Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qB3vwV_wEfGdK7nrvVK6_Q" x="1328" y="122" width="180" height="89"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_apepgVpKEfGye-OBcXLvfQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_apepglpKEfGye-OBcXLvfQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_apepg1pKEfGye-OBcXLvfQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_apeph1pKEfGye-OBcXLvfQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_apephFpKEfGye-OBcXLvfQ" x="53" y="10" width="1742" height="469"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_WEfAUF6oEfGm4rYpAOnikw" type="3007" element="_WEdLIF6oEfGm4rYpAOnikw">
          <children xmi:type="notation:DecorationNode" xmi:id="_WEfAVV6oEfGm4rYpAOnikw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_WEfAVl6oEfGm4rYpAOnikw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_cBP50F6oEfGm4rYpAOnikw" type="3005" element="_cBPSoF6oEfGm4rYpAOnikw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_cBP50V6oEfGm4rYpAOnikw" type="5005" element="_cBPSoF6oEfGm4rYpAOnikw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cBP50l6oEfGm4rYpAOnikw" x="297" y="72" width="181" height="91"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ND1FYF_rEfGnB9X6Ra0WDg" type="3008" element="_ND0eUF_rEfGnB9X6Ra0WDg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ND1FYV_rEfGnB9X6Ra0WDg" type="5026" element="_ND0eUF_rEfGnB9X6Ra0WDg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ND1FYl_rEfGnB9X6Ra0WDg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ND1FY1_rEfGnB9X6Ra0WDg" x="721" y="89" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XXefdF_rEfGnB9X6Ra0WDg" type="3003" element="_XXefcF_rEfGnB9X6Ra0WDg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_XXefdV_rEfGnB9X6Ra0WDg" type="5025" element="_XXefcF_rEfGnB9X6Ra0WDg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XXefdl_rEfGnB9X6Ra0WDg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XXefd1_rEfGnB9X6Ra0WDg" x="1135" y="96"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_R_TAaGAYEfGe7t4W32Y_Cw" type="3027" element="_R_SZUGAYEfGe7t4W32Y_Cw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_R_TAamAYEfGe7t4W32Y_Cw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_R_TAaWAYEfGe7t4W32Y_Cw" x="835" y="70" width="188" height="94"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_WEfAUV6oEfGm4rYpAOnikw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_WEfAUl6oEfGm4rYpAOnikw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_WEfAU16oEfGm4rYpAOnikw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_WEfAV16oEfGm4rYpAOnikw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WEfAVF6oEfGm4rYpAOnikw" x="53" y="603" width="1742" height="263"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_lKqbMVpIEfGye-OBcXLvfQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_lKqbMlpIEfGye-OBcXLvfQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_lKqbM1pIEfGye-OBcXLvfQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_lKrCQlpIEfGye-OBcXLvfQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lKqbNFpIEfGye-OBcXLvfQ" width="1770" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_SFLYXVpIEfGye-OBcXLvfQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_RdYQ5FpLEfGye-OBcXLvfQ" type="4001" element="_RdYQ4VpLEfGye-OBcXLvfQ" source="_OIJacFpLEfGye-OBcXLvfQ" target="_qjadiF32EfG6RKjpA2FJ2g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RdYQ51pLEfGye-OBcXLvfQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RdYQ6FpLEfGye-OBcXLvfQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RdYQ5VpLEfGye-OBcXLvfQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RdYQ5lpLEfGye-OBcXLvfQ" points="[15, 7, -263, 1]$[274, 7, -4, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vuyBgF_rEfGnB9X6Ra0WDg" id="(0.8837209302325582,0.46511627906976744)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2ygUQFpLEfGye-OBcXLvfQ" id="(0.021739130434782608,0.4782608695652174)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_R9yPTlpLEfGye-OBcXLvfQ" type="4001" element="_R9yPS1pLEfGye-OBcXLvfQ" source="_OIJacFpLEfGye-OBcXLvfQ" target="_qBhRYF32EfG6RKjpA2FJ2g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_R9y2UlpLEfGye-OBcXLvfQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_R9y2U1pLEfGye-OBcXLvfQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_R9y2UFpLEfGye-OBcXLvfQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_R9y2UVpLEfGye-OBcXLvfQ" points="[-1, -20, -261, 99]$[-1, -131, -261, -12]$[170, -131, -90, -12]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SllPHlpLEfGye-OBcXLvfQ" type="4001" element="_SllPG1pLEfGye-OBcXLvfQ" source="_OIJacFpLEfGye-OBcXLvfQ" target="_SllPGFpLEfGye-OBcXLvfQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Sll2IFpLEfGye-OBcXLvfQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Sll2IVpLEfGye-OBcXLvfQ" x="33" y="-19"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SllPH1pLEfGye-OBcXLvfQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SllPIFpLEfGye-OBcXLvfQ" points="[-1, 20, -261, -136]$[-1, 153, -261, -3]$[166, 153, -94, -3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DB5CQlpMEfGye-OBcXLvfQ" type="4001" element="_DB4bN1pMEfGye-OBcXLvfQ" source="_qBhRYF32EfG6RKjpA2FJ2g" target="_JqDCBFpMEfGye-OBcXLvfQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DB5CRVpMEfGye-OBcXLvfQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DB5CRlpMEfGye-OBcXLvfQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DB5CQ1pMEfGye-OBcXLvfQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DB5CRFpMEfGye-OBcXLvfQ" points="[3, 0, -105, -92]$[107, 0, -1, -92]$[107, 72, -1, -20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FUYCQFpMEfGye-OBcXLvfQ" id="(0.9835164835164835,0.14285714285714285)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KVlSUFpMEfGye-OBcXLvfQ" type="4001" element="_KVkrQFpMEfGye-OBcXLvfQ" source="_qjadiF32EfG6RKjpA2FJ2g" target="_JqDCBFpMEfGye-OBcXLvfQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KVlSU1pMEfGye-OBcXLvfQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KVlSVFpMEfGye-OBcXLvfQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KVlSUVpMEfGye-OBcXLvfQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KVlSUlpMEfGye-OBcXLvfQ" points="[0, 33, -103, 92]$[100, 33, -3, 92]$[100, -41, -3, 18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KVl5YFpMEfGye-OBcXLvfQ" id="(1.0,0.32608695652173914)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MeQPAFpMEfGye-OBcXLvfQ" type="4001" element="_MeKIYFpMEfGye-OBcXLvfQ" source="__Ef1FFpKEfGye-OBcXLvfQ" target="_JqDCBFpMEfGye-OBcXLvfQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MeQPA1pMEfGye-OBcXLvfQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MeQPBFpMEfGye-OBcXLvfQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MeQPAVpMEfGye-OBcXLvfQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MeQPAlpMEfGye-OBcXLvfQ" points="[-24, -26, -857, -102]$[-24, -60, -857, -136]$[832, -60, -1, -136]$[832, 56, -1, -20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MeRdIFpMEfGye-OBcXLvfQ" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_W5RcY1pMEfGye-OBcXLvfQ" type="4001" element="_W5RcYFpMEfGye-OBcXLvfQ" source="_SllPGFpLEfGye-OBcXLvfQ" target="_W5Q1VFpMEfGye-OBcXLvfQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_W5RcZlpMEfGye-OBcXLvfQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_W5RcZ1pMEfGye-OBcXLvfQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_W5RcZFpMEfGye-OBcXLvfQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_W5RcZVpMEfGye-OBcXLvfQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oGWTQF34EfGU_4a8meDJCw" type="4001" element="_oGVFIF34EfGU_4a8meDJCw" source="_jrCJkFpKEfGye-OBcXLvfQ" target="_nbrloF34EfGU_4a8meDJCw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oGW6UF34EfGU_4a8meDJCw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oGW6UV34EfGU_4a8meDJCw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oGWTQV34EfGU_4a8meDJCw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oGWTQl34EfGU_4a8meDJCw" points="[-1, -13, -32, 4]$[31, 1, 0, 18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oGYvgF34EfGU_4a8meDJCw" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oGYvgV34EfGU_4a8meDJCw" id="(0.01,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__P1HUF6oEfGm4rYpAOnikw" type="4001" element="__Pz5MF6oEfGm4rYpAOnikw" source="_JqDCBFpMEfGye-OBcXLvfQ" target="_qB3vwF_wEfGdK7nrvVK6_Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__P1HU16oEfGm4rYpAOnikw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__P1HVF6oEfGm4rYpAOnikw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__P1HUV6oEfGm4rYpAOnikw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__P1HUl6oEfGm4rYpAOnikw" points="[-8, 0, -107, 12]$[100, 21, 1, 33]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__P3jkF6oEfGm4rYpAOnikw" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__P3jkV6oEfGm4rYpAOnikw" id="(0.13812154696132597,0.5222222222222223)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__v2EIF6oEfGm4rYpAOnikw" type="4001" element="__v1dEF6oEfGm4rYpAOnikw" source="_qB3vwF_wEfGdK7nrvVK6_Q" target="_TWi8gFpMEfGye-OBcXLvfQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__v2EI16oEfGm4rYpAOnikw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__v2EJF6oEfGm4rYpAOnikw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__v2EIV6oEfGm4rYpAOnikw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__v2EIl6oEfGm4rYpAOnikw" points="[0, 7, -126, 1]$[127, -2, 1, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__v3SQF6oEfGm4rYpAOnikw" id="(1.0,0.3888888888888889)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__v3SQV6oEfGm4rYpAOnikw" id="(0.16666666666666666,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hS_0wF_oEfGm4rYpAOnikw" type="4001" element="_hS01oF_oEfGm4rYpAOnikw" source="__Ef1FFpKEfGye-OBcXLvfQ" target="_cBP50F6oEfGm4rYpAOnikw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hTAb0F_oEfGm4rYpAOnikw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hTAb0V_oEfGm4rYpAOnikw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hS_0wV_oEfGm4rYpAOnikw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hS_0wl_oEfGm4rYpAOnikw" points="[0, -9, 12, -444]$[-12, 425, 0, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hTCRAF_oEfGm4rYpAOnikw" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hTCRAV_oEfGm4rYpAOnikw" id="(0.569060773480663,0.15384615384615385)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hzAKgF_oEfGm4rYpAOnikw" type="4001" element="_hy-8YF_oEfGm4rYpAOnikw" source="_nbrloF34EfGU_4a8meDJCw" target="__Ef1FFpKEfGye-OBcXLvfQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hzAKg1_oEfGm4rYpAOnikw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hzAKhF_oEfGm4rYpAOnikw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hzAKgV_oEfGm4rYpAOnikw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hzAKgl_oEfGm4rYpAOnikw" points="[0, -1, -98, -4]$[102, -10, 4, -13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hzB_sF_oEfGm4rYpAOnikw" id="(1.0,0.4358974358974359)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PdBxYF_rEfGnB9X6Ra0WDg" type="4001" element="_PdBKUF_rEfGnB9X6Ra0WDg" source="_cBP50F6oEfGm4rYpAOnikw" target="_ND1FYF_rEfGnB9X6Ra0WDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PdBxY1_rEfGnB9X6Ra0WDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PdBxZF_rEfGnB9X6Ra0WDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PdBxYV_rEfGnB9X6Ra0WDg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PdBxYl_rEfGnB9X6Ra0WDg" points="[0, 0, -114, 11]$[114, -9, 0, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PdENoF_rEfGnB9X6Ra0WDg" id="(1.0,0.3956043956043956)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PdENoV_rEfGnB9X6Ra0WDg" id="(0.09302325581395349,0.5116279069767442)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Qt0q4F_rEfGnB9X6Ra0WDg" type="4001" element="_QtzcwF_rEfGnB9X6Ra0WDg" source="_ND1FYF_rEfGnB9X6Ra0WDg" target="_OIJacFpLEfGye-OBcXLvfQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Qt1R8F_rEfGnB9X6Ra0WDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Qt1R8V_rEfGnB9X6Ra0WDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Qt0q4V_rEfGnB9X6Ra0WDg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Qt0q4l_rEfGnB9X6Ra0WDg" points="[-12, -22, -130, 353]$[117, -376, -1, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Qt3uMF_rEfGnB9X6Ra0WDg" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Qt3uMV_rEfGnB9X6Ra0WDg" id="(0.23255813953488372,0.3023255813953488)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UNvuYF_rEfGnB9X6Ra0WDg" type="4001" element="_UNlWUF_rEfGnB9X6Ra0WDg" source="_ND1FYF_rEfGnB9X6Ra0WDg" target="_R_TAaGAYEfGe7t4W32Y_Cw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UNwVcF_rEfGnB9X6Ra0WDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UNwVcV_rEfGnB9X6Ra0WDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UNvuYV_rEfGnB9X6Ra0WDg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UNvuYl_rEfGnB9X6Ra0WDg" points="[-6, -4, -68, 1]$[63, 30, 1, 35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UNyKoF_rEfGnB9X6Ra0WDg" id="(1.0,0.813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UNyKoV_rEfGnB9X6Ra0WDg" id="(0.06382978723404255,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Z_BwgF_rEfGnB9X6Ra0WDg" type="4001" element="_Z_BJcF_rEfGnB9X6Ra0WDg" source="_R_TAaGAYEfGe7t4W32Y_Cw" target="_XXefdF_rEfGnB9X6Ra0WDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Z_Bwg1_rEfGnB9X6Ra0WDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Z_BwhF_rEfGnB9X6Ra0WDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Z_BwgV_rEfGnB9X6Ra0WDg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Z_Bwgl_rEfGnB9X6Ra0WDg" points="[0, 2, -84, 1]$[85, 5, 1, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Z_C-oF_rEfGnB9X6Ra0WDg" id="(1.0,0.40425531914893614)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Z_C-oV_rEfGnB9X6Ra0WDg" id="(0.0,0.43333333333333335)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
